# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      docker-compose -f $(System.DefaultWorkingDirectory)/docker-compose.yml build
      docker images
      docker save $(docker-compose -f $(System.DefaultWorkingDirectory)/docker-compose.yml config --services) > compose-images.tar
    displayName: 'Build images'

  - script: |
      cd '$(System.DefaultWorkingDirectory)'
      ls -lSha
    displayName: 'Find Artifact'

  #- task: CopyFilesOverSSH@2
  #  displayName: 'Copy tar files to server'
  #  inputs:
  #    sshEndpoint: 'your-ssh-endpoint'
  #    sourceFolder: '$(System.DefaultWorkingDirectory)'
  #    contents: '**/*.tar'
  #    targetFolder: '/path/to/deployment/folder'
  #    cleanTargetFolder: true
  #    overwrite: true