# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      docker-compose -f **/docker-compose.yml build
      docker images
    displayName: 'Build images'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'tar'
      tarFile: 'example-webapp.tar'
      archiveFiles: '**/example-webapp/*.dockerfile'
    displayName: 'Archive example-webapp image'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'tar'
      tarFile: 'example-proxy.tar'
      archiveFiles: '**/example-proxy/*.dockerfile'
    displayName: 'Archive example-proxy image'

  - script: |
      cd '$(System.DefaultWorkingDirectory)'
      ls -lSha
    displayName: 'Find Artifact'

  #- task: CopyFilesOverSSH@2
  #  displayName: 'Copy tar files to server'
  #  inputs:
  #    sshEndpoint: 'your-ssh-endpoint'
  #    sourceFolder: '$(System.DefaultWorkingDirectory)'
  #    contents: '**/*.tar'
  #    targetFolder: '/path/to/deployment/folder'
  #    cleanTargetFolder: true
  #    overwrite: true