version: '3'

services:
  webapp:
    build: ./webapp
    expose:
      - "3000"
    scale: 6
    restart: on-failure
    environment:
      - DOCKER_RESTRICTED=true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s

  webapp-proxy:
    build: ./webapp-proxy
    ports:
      - "80:80"
    depends_on:
      - webapp
    restart: always